doctrine:
    dbal:
#        url: '%env(resolve:DATABASE_URL)%'
        dbname: '%env(resolve:DBNAME)%'
        host: '%env(resolve:DB_HOST)%'
        port: '%env(resolve:DB_PORT)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PW)%'
        driver: '%env(resolve:DB_DRIVER)%'
#        unix_socket: /tmp/mysql.sock

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
